### ISSUE TITLE
currentTime is null - audio context is not started when urlparam mode=play is in the URL

### ISSUE THREAD

**Issue by shark8me** [Studio-kalavati/bandish-editor#102]
how to reproduce:
Click on URL https://swaranotebook.com/view/vlB9hVgb5OdKcadbhOOYyzKwvpl2/1401aaf6d244-Rasputin-boneym?mode=play&bpm=180 and play.
It fails because the audiocontext is not started.

**Comment by shark8me** [comment]
```
Uncaught TypeError: Cannot read properties of null (reading 'currentTime')
    at app.js:6883:206
    at app.js:5703:453
    at app.js:5703:469
    at re_frame.interceptor.invoke_interceptor_fn (app.js:5479:464)
    at re_frame.interceptor.invoke_interceptors (app.js:5480:269)
    at re_frame.interceptor.execute (app.js:5486:394)
    at re_frame.events.handle (app.js:5499:494)
    at re_frame.router.EventQueue.re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1 (app.js:5629:170)
    at re_frame.router.EventQueue.re_frame$router$IEventQueue$_run_queue$arity$1 (app.js:5599:475)
    at app.js:5621:202
```
