### ISSUE TITLE
Google / Firebase auth works locally but fails on Netlify

### ISSUE THREAD

**Issue by shark8me** [Studio-kalavati/Bandish-editor#6]
```
app.js:3332 Uncaught TypeError: a.Eq is not a function
    at app.js:3332:81
    at r_ (app.js:3333:366)
    at app.js:3348:26
    at app.js:2596:484
    at jN (app.js:2581:174)
    at mN (app.js:2581:545)
    at xN (app.js:2594:38)
    at vN (app.js:2590:449)
    at app.js:2592:241
    at wN (app.js:2593:298)
```

**Comment by shark8me** [comment]
use compiler option setting simple
